spring:
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level.com.sidedish: debug
