spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sidedishDB
    username: root
    password: qwepoi1209!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
